name: MSBuild

on: [push]
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run test
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ${{env.GITHUB_WORKSPACE}}/gibbit.exe
